#!/bin/bash

# create-offline-cache.sh - Create npm-packages-offline-cache for Cloud Foundry offline deployment
#
# This script creates the official Cloud Foundry offline cache directory
# as documented at: https://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring
#
# The buildpack will detect this directory and run in offline mode,
# eliminating the need for external npm/yarn registry access during staging.

set -e

echo "========================================="
echo "Creating Offline Package Cache"
echo "========================================="
echo ""

# Check if yarn is installed
if ! command -v yarn &> /dev/null; then
    echo "⚠ Yarn is not installed. Installing yarn globally..."
    npm install -g yarn
    echo "✓ Yarn installed successfully"
    echo ""
fi

# Clean previous cache and dependencies
echo "→ Cleaning previous cache and dependencies..."
rm -rf npm-packages-offline-cache node_modules yarn.lock .yarnrc

# Create .yarnrc file directly with correct relative path
echo "→ Creating Yarn offline configuration..."
cat > .yarnrc << 'EOF'
# Yarn offline mirror configuration
# This file is auto-generated by create-offline-cache.sh
yarn-offline-mirror "./npm-packages-offline-cache"
yarn-offline-mirror-pruning true
EOF

echo "  ✓ Created .yarnrc with offline mirror configuration"

# Verify .yarnrc content
echo ""
echo "→ Verifying .yarnrc configuration..."
cat .yarnrc
echo ""

# Install dependencies (this creates the offline cache)
echo "→ Installing dependencies and creating offline cache..."
yarn install --production

# Verify offline cache was created
if [ ! -d "npm-packages-offline-cache" ]; then
    echo ""
    echo "✗ ERROR: npm-packages-offline-cache was not created!"
    echo ""
    echo "Debugging information:"
    echo "  - Current directory: $(pwd)"
    echo "  - .yarnrc exists: $([ -f .yarnrc ] && echo 'yes' || echo 'no')"
    echo "  - .yarnrc content:"
    cat .yarnrc 2>/dev/null || echo "    (file not found)"
    echo ""
    exit 1
fi

# Count cached packages
CACHE_COUNT=$(ls -1 npm-packages-offline-cache/*.tgz 2>/dev/null | wc -l | tr -d ' ')
CACHE_SIZE=$(du -sh npm-packages-offline-cache 2>/dev/null | cut -f1)

echo ""
echo "========================================="
echo "✓ Offline cache created successfully!"
echo "========================================="
echo "  Cache directory: npm-packages-offline-cache/"
echo "  Cached packages: $CACHE_COUNT .tgz files"
echo "  Cache size: $CACHE_SIZE"
echo ""
echo "Files created:"
echo "  • npm-packages-offline-cache/ - Offline package cache"
echo "  • .yarnrc - Yarn offline configuration"
echo "  • yarn.lock - Dependency lock file"
echo "  • node_modules/ - Local dependencies (optional for CF)"
echo ""
echo "========================================="
echo "Next steps:"
echo "========================================="
echo "1. Verify cache contents:"
echo "   ls -lh npm-packages-offline-cache/"
echo ""
echo "2. Deploy to Cloud Foundry:"
echo "   cf push -f manifest.yml"
echo ""
echo "3. Buildpack will detect offline cache and run:"
echo "   'Running yarn in offline mode'"
echo ""
echo "Note: The buildpack will use npm-packages-offline-cache"
echo "      and does NOT require node_modules to be uploaded."
echo ""
